# Generated by Django 6.0.3 on 2026-03-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDocumentationVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=100, unique=True)),
                ('schema', models.JSONField(help_text='Full OpenAPI schema JSON')),
                ('endpoint_hashes', models.JSONField(default=dict, help_text="Mapping of 'METHOD:/path/' to hash of operation schema")),
                ('changes_summary', models.JSONField(blank=True, help_text='Diff vs previous version: {new: [...], modified: [...], removed: [...]}', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
    ]
