name: Release Python Package

on:
  push:
    branches:
      - release
      - test_release
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/packaging.txt
      - name: Build distributions
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish to TestPyPI
        if: github.ref == 'refs/heads/test_release'
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        run: |
          python -m twine upload --skip-existing dist/*
      - name: Publish to PyPI
        if: github.ref == 'refs/heads/release'
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload --skip-existing dist/*